### ISSUE TITLE
Further explanatory materials anywhere?

### ISSUE THREAD

**Issue by TTD1024** [adamb314/ServoProject#11]
Excuse me, this is an absolutely excellent project, but while the documentation is great for using the completed system as you have produced it (great work), it doesn't give a detailed description of th underlying theory. Might you be able to provide some links to where you learnt the excellent PID and control techniques* you've employed here, or otherwise some further description of how the double-encoder feedback loop works (more detailed than the diagram presently shown for comparison to classical hobby servo control loops, but more explanatory that just trying to interpret source code)? Any links on where to learn this stuff and truly undertand it would be really welcome, and could help others in applying the core principles of this brilliant project to a wider variety of servo types and geometries.
Thank you

*particularly how you manage to make a DC motor behave as if it were proportional despite the fact that they typically won't move at all until some threshold PWM level is crossed and then they suddenly start moving quite fast

**Comment by adamb314** [comment]
Glad you like the project! I am currently working on a lot of improvements on the project, including a new implementation of the system identification part. I hope to be able to also add some more documentation in the process. The development branch already has an extra theory section called "Calculating the control parameters", if you have not seen it.

The PWM compensation you asked about is quite simple. The current implementation relies on the fact that the motor torque is proportional to the current (ignoring any losses from resistance). In the pwm calibration step you input the current draw for different pwm levels and that is used to create a simple lookup table. The servo then uses this to translate the required torque into the correct pwm value (implemented in the class CurrentControlModel).
If you measure the current draw of the motor, when you do the test you described, you will see that the current stays very low until you hit the pwm offset.

May I ask you which of my PCB designs you have tried and at which PWM frequency? I recently found out that there is an EMI problem with the PCB design in the ServoBrushed folder that limits the pwm frequency and wonder if anyone has had any problems with it.

**Comment by TTD1024** [comment]
Thank you.

That PWM compensation looks a very clever way to handle that problem simply and in a way which remains valid when having different torque demands on the servo.

I have not tried the PCB designs, I am more interested in understanding the underlying logic of your software so I can implement it with a different MCU type for use with different form factors of servo and other forms of encoder.

Thank you for your reply, I'll await seeing the extra documentation when it appears, thanks again for replying.
