### ISSUE TITLE
Issue with running configurationWizard script on Windows

### ISSUE THREAD

**Issue by PointyyP** [adamb314/ServoProject#14]
I've installed MSYS2 and the PyGObject package, however an error "no such file or directory" occurs when trying to run the script.

**Comment by adamb314** [comment]
What happens if you try to run just:
'C:\msys64\mingw64\bin\python.exe'

If that works, have you changed working directory to the ServoProject folder?

I do not have a Windows computer to test it on my self at the moment... but if you still have problems I will look in to it!

**Comment by PointyyP** [comment]
Thanks for the fast reply! Looks like fixing the directory helped. However, I have a new error.
![image](https://github.com/adamb314/ServoProject/assets/146996873/22667e85-5e98-404a-905a-beb330196295)

**Comment by smith901** [comment]
I got a notification for this issue and don't know why.   

After reading & looking at the error, seems like you need to install GTK3 on your machine: `Python/ServoProjectModules/GuiHelper.py:6` gi.require_version("Gtk", "3.0")

GTK does have MYSYS2 install instruction. I only use my Windows machine for offline business stuff. Hope this helps.

**Comment by PointyyP** [comment]
It worked! Thank you so much!
![image](https://github.com/adamb314/ServoProject/assets/146996873/c9f5925c-5cc1-40b9-b4f9-200e184aedbc)
