### ISSUE TITLE
How did you measure the laser angle in the comparison? What was your setup in the video "How to make your servos awesome"?

### ISSUE THREAD

**Issue by PointyyP** [adamb314/ServoProject#17]
How did you obtain the data from the responses by the regular servos and the modded servos?
![image](https://github.com/adamb314/ServoProject/assets/146996873/30767dfa-de65-4d05-9c20-c89a704bb91d)

**Comment by adamb314** [comment]
I put a tape measure about 2 m away from the servo and recorded a video of the laser dots movement on the tape. Then I used a python script and openCV to calculate the angle over time from the video.

![Screenshot_20231122_104415_Photos.jpg](https://github.com/adamb314/ServoProject/assets/82474186/b21d9853-0482-49c4-9f9a-ce78dfa8d478)

**Comment by PointyyP** [comment]
Do you still have the data from a spreadsheet?
