### ISSUE TITLE
Simpler feedback

### ISSUE THREAD

**Issue by mrx23dot** [adamb314/ServoProject#23]
You could try painting the end of motor shaft half black and look for reflections, it would require less modification.

I was also thinking doing it with BEMF detection but that's unreliable at low speeds and need calibration.

also have a look at this, it has GUI to configure
https://github.com/ginge/OpenServo/tree/master/OpenServo/AVR_OpenServo_V3

**Comment by adamb314** [comment]
That would only give me 4 pulses per revolution. My current implementation, with the off-center disc, results in 2048 positions per revolution since it uses the analog values from the two sensors.

**Comment by mrx23dot** [comment]
I meant for the project with the long arm and backlash compensation,
since the ratio between motor and output arm is huge it might not matter that much.
